name: Publish to AWS
run-name: ${{ github.actor }} is publishing to the AWS lightsail instance
on:
  push:
    branches: [main]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish Action
      run: curl $Host?passkey=$PassKey
      env:
        Host: ${{ secrets.HOST }}
        PassKey: ${{ secrets.PASSKEY}}


